/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgnew;

import java.awt.CardLayout;
import static pkgnew.Main_Frame.Display;
import static pkgnew.Main_Frame.DisplayPanel;
import static pkgnew.Main_Frame.card;
/**
 *
 * @author priyanja
 */
public class Subcategory_Books extends javax.swing.JPanel {

    /**
     * Creates new form Subcategory_Books
     */
    public Subcategory_Books() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cse = new javax.swing.JLabel();
        ece = new javax.swing.JLabel();
        mech = new javax.swing.JLabel();
        chemical = new javax.swing.JLabel();
        biotech = new javax.swing.JLabel();
        civil = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        cse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgnew/rsz_cse.png"))); // NOI18N
        cse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cseMouseClicked(evt);
            }
        });

        ece.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgnew/rsz_1ece.png"))); // NOI18N
        ece.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eceMouseClicked(evt);
            }
        });

        mech.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgnew/rsz_mech.png"))); // NOI18N
        mech.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mechMouseClicked(evt);
            }
        });

        chemical.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgnew/rsz_chemicals.png"))); // NOI18N
        chemical.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chemicalMouseClicked(evt);
            }
        });

        biotech.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgnew/rsz_biotech.png"))); // NOI18N
        biotech.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                biotechMouseClicked(evt);
            }
        });

        civil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgnew/rsz_civil.png"))); // NOI18N
        civil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                civilMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel7.setText("BOOKS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(367, 367, 367)
                .addComponent(jLabel7)
                .addContainerGap(417, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 32, Short.MAX_VALUE)
                .addComponent(jLabel7))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chemical, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ece, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(biotech, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mech, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(civil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(73, 73, 73))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(biotech, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mech, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cse, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ece, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addComponent(chemical, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(civil, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(153, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cseMouseClicked
        // TODO add your handling code here:
         CardLayout Card = (CardLayout)DisplayPanel.getLayout();
         card = "list_items";
        Card.show(DisplayPanel, "list_items");
        Display("Books","Cse/It");
    }//GEN-LAST:event_cseMouseClicked

    private void eceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eceMouseClicked
        // TODO add your handling code here:
        CardLayout Card = (CardLayout)DisplayPanel.getLayout();
        Card.show(DisplayPanel, "list_items");
        card = "list_items";
        Display("Books","Ece/Electrical");
    }//GEN-LAST:event_eceMouseClicked

    private void mechMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mechMouseClicked
        // TODO add your handling code here:
        CardLayout Card = (CardLayout)DisplayPanel.getLayout();
        card = "list_items";
        Card.show(DisplayPanel, "list_items");
        Display("Books","Mech/Prod");
    }//GEN-LAST:event_mechMouseClicked

    private void chemicalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chemicalMouseClicked
        // TODO add your handling code here:
        CardLayout Card = (CardLayout)DisplayPanel.getLayout();
        card = "list_items";
        Card.show(DisplayPanel, "list_items");
        Display("Books","Chemical");
    }//GEN-LAST:event_chemicalMouseClicked

    private void biotechMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_biotechMouseClicked
        // TODO add your handling code here:
        CardLayout Card = (CardLayout)DisplayPanel.getLayout();
        card = "list_items";
        Card.show(DisplayPanel, "list_items");
        Display("Books","Biotech");
    }//GEN-LAST:event_biotechMouseClicked

    private void civilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_civilMouseClicked
        // TODO add your handling code here:
        CardLayout Card = (CardLayout)DisplayPanel.getLayout();
        card = "list_items";
        Card.show(DisplayPanel, "list_items");
        Display("Books","Civil");
    }//GEN-LAST:event_civilMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel biotech;
    private javax.swing.JLabel chemical;
    private javax.swing.JLabel civil;
    private javax.swing.JLabel cse;
    private javax.swing.JLabel ece;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mech;
    // End of variables declaration//GEN-END:variables
}
