/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectofx;

import java.awt.CardLayout;
import static projectofx.Category.label_User;
 /*
 * @author avishkar
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    
    public static boolean LOGIN=false;
    public static  String  user_login;
    
    
    public MainFrame() {
       
        initComponents();
        Button_back.setVisible(false);
        }

    
     public static void for_user(){
     
         Thread t = new Thread(){
         public void run(){
        
                System.out.println("hey thr can u see me");
                while(true){

                    if(LOGIN==true){
                         label_User.setText("Welcome " + user_login);
                    }
                    else{
                        label_User.setText("");
                    }
                }

            }
         
         };
         t.start();   
     }
      
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DisplayPanel = new javax.swing.JPanel();
        logIn = new projectofx.LogIn();
        signUp = new projectofx.SignUp();
        category1 = new projectofx.Category();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        Button_login = new javax.swing.JButton();
        Button_signup = new javax.swing.JButton();
        Button_back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        DisplayPanel.setLayout(new java.awt.CardLayout());
        DisplayPanel.add(logIn, "login");
        DisplayPanel.add(signUp, "signup");
        DisplayPanel.add(category1, "category");

        getContentPane().add(DisplayPanel);

        Button_login.setText("LOG IN");
        Button_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_loginActionPerformed(evt);
            }
        });

        Button_signup.setText("SIGN UP");
        Button_signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_signupActionPerformed(evt);
            }
        });

        Button_back.setText("BACK");
        Button_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Button_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Button_signup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Button_back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Button_login)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Button_signup)
                .addGap(34, 34, 34)
                .addComponent(Button_back)
                .addContainerGap(381, Short.MAX_VALUE))
        );
        jLayeredPane1.setLayer(Button_login, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Button_signup, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Button_back, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(jLayeredPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_signupActionPerformed
       
        CardLayout card =(CardLayout) DisplayPanel.getLayout();
        card.show(DisplayPanel, "signup");
        Button_signup.setVisible(false);
        Button_login.setVisible(false);
        Button_back.setVisible(true);
        
// TODO add your handling code here:
    }//GEN-LAST:event_Button_signupActionPerformed

    private void Button_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_loginActionPerformed
        CardLayout card =(CardLayout) DisplayPanel.getLayout();
        card.show(DisplayPanel, "login");
        Button_signup.setVisible(false);
        Button_login.setVisible(false);
        Button_back.setVisible(true);
        
// TODO add your handling code here:
    }//GEN-LAST:event_Button_loginActionPerformed

    private void Button_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_backActionPerformed
        
        CardLayout card =(CardLayout) DisplayPanel.getLayout();
        card.show(DisplayPanel, "category");
        Button_signup.setVisible(true);
        Button_login.setVisible(true);
        Button_back.setVisible(false);
        
    // TODO add your handling code here:
    }//GEN-LAST:event_Button_backActionPerformed

    /**
     * @param args the command line arguments
     */
    
    

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
                for_user();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton Button_back;
    public static javax.swing.JButton Button_login;
    public static javax.swing.JButton Button_signup;
    public static javax.swing.JPanel DisplayPanel;
    public static projectofx.Category category1;
    public static javax.swing.JLayeredPane jLayeredPane1;
    public static projectofx.LogIn logIn;
    public static projectofx.SignUp signUp;
    // End of variables declaration//GEN-END:variables
}
